# Generated by Django 5.2.7 on 2026-02-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Имя ребенка", max_length=100, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Фамилия ребенка",
                        max_length=100,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Отчество ребенка",
                        max_length=100,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "cyberons",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество накопленных киберонов",
                        verbose_name="Количество киберонов",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("lead", "Лид"), ("client", "Клиент")],
                        default="lead",
                        help_text="Текущий статус ребенка",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Ребенок",
                "verbose_name_plural": "Дети",
                "ordering": ["last_name", "first_name", "-created_at"],
            },
        ),
    ]
